# Generated by Django 3.2.4 on 2021-06-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Video',
        ),
    ]
