# Generated by Django 3.2.4 on 2021-06-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
